### ISSUE TITLE
Aether Fish

### ISSUE THREAD

**Issue by TunefulTurnip** [TunefulTurnip/Deep-Aether#1]
- [x] Make a model
- [x] Make a texture
- [x] Come up with a name
- [x] add spawn egg, bucket with Aerglow Fish, raw Aerglow Fish item, cooked Aerglow Fish item 
- [x] Copy the cod's ai to the Aerglow Fish
- [x] Make the fish spawn in the Aether
- [x] Give Aerglow Fish an animation

**Comment by darksonic300** [comment]
Done the animation. Will be revised
