### ISSUE TITLE
Incorrect Biome Names

### ISSUE THREAD

**Issue by Eletoast** [TunefulTurnip/Deep-Aether#102]
Sorry if this title is a little misleading, but when using a mod like Xaero's Minimap (like in the image provided) the incorrect name is shown when having biome names shown.
![Screenshot 2023-10-02 165104](https://github.com/RazorDevs/Deep-Aether/assets/143987495/4d3f74d7-092c-4a40-b3fb-feff81c99b5c)

**Comment by darksonic300** [comment]
Will be fixed by next beta.
