### ISSUE TITLE
Feature: Aether Dragonfly / Venomite

### ISSUE THREAD

**Issue by darksonic300** [TunefulTurnip/Deep-Aether#110]
A new mob that will spawn in the Yagroot Swamps.
Will most probably be a neutral mob that won't use Poison attacks.
They'll drop their wings or eyes for utility and repair uses (Potions, ecc.)

Affected by bane of Anthropods

Maybe they could act like a sort of bees too but have a different utlility.

Maybe it will have a poison sack that when killed drops on the ground and gives a lingering inebriation cloud

The model would be a sort of green and purple dragonfly with some Vines attached and a bit of a scary look.

- [x] Model
- [x] AI
- [x] Texture
- [x] General Behaviour

**Comment by 345boneshoss** [comment]
I have no idea how to make mobs or animate them. lol

Still a VERY good idea!
