### ISSUE TITLE
Error with a strcture

### ISSUE THREAD

**Issue by BlitzHayato** [TunefulTurnip/Deep-Aether#111]
Got this on launch, would explain my server lag.

20.10 03:28:52 [Server] Worker-Main5/WARN [ModernFix/]: The namespace aether contains an outdated structure file, which can cause worldgen lag. Please view debug.log for the full filename, determine which mod provides the structure, and report to the mod/datapack author, including the debug log.
20.10 03:28:52 [Server] Worker-Main3/WARN [ModernFix/]: The namespace deep_aether contains an outdated structure file, which can cause worldgen lag. Please view debug.log for the full filename, determine which mod provides the structure, and report to the mod/datapack author, including the debug log.
[debug.log](https://github.com/RazorDevs/Deep-Aether/files/13049695/debug.log)

**Comment by darksonic300** [comment]
I suggest to report this to Aether's Issue tracker too.

**Comment by darksonic300** [comment]
Seems like latest version of ModernFix uses cached updated versions, so I'll mark this as fixed.
