### ISSUE TITLE
[1.19.2] - Latest Update (1.0.1) Breaks Harvesting 

### ISSUE THREAD

**Issue by PhweeDev** [TunefulTurnip/Deep-Aether#125]
Hello,

I was playing with my friend and this update had come out. So I updated it and it turns out we couldn't use our pickaxes to mine anything. Something in the new update broke harvestability for most everything. Shovels and hoes seem to work fine in harvesting, but axes and pickaxes are broken. I'm talking about in vanilla, not just the Aether. Hopefully you can look into this and release a quick fix.

**Comment by Raphe9000** [comment]
I got the exact same problem; all pickaxes were acting as if I was using my hand to mine instead. Not sure if it has to do with some other mod interaction or not, but reverting back to the previous update did fix it.

**Comment by Eletoast** [comment]
Seems like it's a mod incompatibility, as it runs fine for me. If you could send a mod list, it would probably help the devs.

**Comment by darksonic300** [comment]
Let me check a couple of thing and we'll probably get a fix out really soon
