### ISSUE TITLE
Virulent Path block has wrong texture, and Virulent Grass block can't be converted into path block

### ISSUE THREAD

**Issue by 345boneshoss** [TunefulTurnip/Deep-Aether#13]
Hopefully, this will be fixed. In terms of the hand model, it has the same issue as the Aerglow Grass Path.
![image](https://user-images.githubusercontent.com/107210046/174134755-68879c40-cf68-42c0-953c-ee9157ee27d3.png)

**Comment by darksonic300** [comment]
No Grass blocks anymore
