### ISSUE TITLE
mixin crashes

### ISSUE THREAD

**Issue by AnAwesomGuy** [TunefulTurnip/Deep-Aether#132]
https://github.com/RazorDevs/Deep-Aether/blob/dce9d51013c15565b80b69821eb0b217c010ea05/src/main/java/teamrazor/deepaether/mixin/LivingEntityValorMixin.java#L26
you shouldnt assume that magic damage comes from a livingentity, what about tipped arrows and splash potions?
also, couldnt you just use an event for this?

[crash log (not mine, it was reported in the mmc discord server)](https://github.com/RazorDevs/Deep-Aether/files/13804350/crash-2024-01-01_05.59.55-server.txt)

**Comment by darksonic300** [comment]
yes and yes. Fix coming later today.
