### ISSUE TITLE
LivingEntity.handler$zoc000$deep_aether$checkValkValorEffect

### ISSUE THREAD

**Issue by Yovez** [TunefulTurnip/Deep-Aether#133]
Having a common crash with this mod while using Create, specifically using Trains. If a train runs into an entity the server crashes. Logs here: https://mclo.gs/Mp2qKDb

I made an issue post on Create github, but it seems to be a direct issue from Deep Aether.

With Deep Aether, using a train and hitting a mob with the train it crashes.
Without Deep Aether, using a train and hitting a mob works as intended, pushes and damages the mob, no issues.

Edit:
MC 1.20.1
Forge 47.2.0
Create 0.5.1.f
Deep Aether 1.0.13

**Comment by darksonic300** [comment]
The issue should be already fixed, and a hotfix is coming later today to account for this.
