### ISSUE TITLE
Bug: Sun Core might be dropped even though the player took effective damage.

### ISSUE THREAD

**Issue by darksonic300** [TunefulTurnip/Deep-Aether#134]
No testing done yet, but in a recent video posted to youtube, the player took consistent damage in his fight against the Sun Spirit. Despite this the Sun Core was dropped anyway even though it shouldn't have.

**Comment by TunefulTurnip** [comment]
Can't replicate this issue. If anyone has a similar issue, please open a new issue with a proper log.
