### ISSUE TITLE
[Rel: Create] ClassCastException: CarriageContraptionEntity cannot be cast to class LivingEntity

### ISSUE THREAD

**Issue by burdoto** [TunefulTurnip/Deep-Aether#135]
As reported in https://github.com/Creators-of-Create/Create/issues/5963:

### Describe the Bug

This exception started occurring irregularly today.

### Reproduction Steps

unsure

### Expected Result

no crash

### Crash Report or Log

https://hastebin.com/share/ufuruwuloj.wasm

### Operating System

archlinux

### Minecraft Version

1.20.1

### Forge Version

arclight-1.20.1-1.0.2-SNAPSHOT-71acd73 (MC: 1.20.1)

### Other Mods

		YungsBetterDungeons-1.20-Forge-4.0.3.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		create_misc_and_things_ 1.20.1_4.0A.jar           |create: things and misc       |create_things_and_misc        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.20.1-1.3.30.jar                      |Blue Skies                    |blue_skies                    |1.3.30              |DONE      |Manifest: NOSIGNATURE
		netherportalfix-forge-1.20-13.0.1.jar             |NetherPortalFix               |netherportalfix               |13.0.1              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.3.1.jar                   |GeckoLib 4                    |geckolib                      |4.3.1               |DONE      |Manifest: NOSIGNATURE
		deepslatecutting-forge-1.7.0.jar                  |DeepslateCutting              |deepslatecutting_forge        |1.7.0               |DONE      |Manifest: NOSIGNATURE
		aether-1.20.1-1.0.0-neoforge.jar                  |The Aether                    |aether                        |1.20.1-1.0.0-neoforg|DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.20.1forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.113.524.jar          |Sophisticated Core            |sophisticatedcore             |0.5.113.524         |DONE      |Manifest: NOSIGNATURE
		structureessentials-1.20.1-3.2.jar                |Structure Essentials mod      |structureessentials           |1.20.1-3.2          |DONE      |Manifest: NOSIGNATURE
		mcwfurnituresbop-1.20-1.1.jar                     |Macaw's Furnitures - BOP      |mcwfurnituresbop              |1.20-1.1            |DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.20-16.0.1.jar        |CookingForBlockheads          |cookingforblockheads          |16.0.1              |DONE      |Manifest: NOSIGNATURE
		Prism-1.20.1-forge-1.0.5.jar                      |Prism                         |prism                         |1.0.5               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.20.1-8.6.0.jar                          |Placebo                       |placebo                       |8.6.0               |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.9-1.20.1.jar                          |Citadel                       |citadel                       |2.4.9               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.7.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.7              |DONE      |Manifest: NOSIGNATURE
		everythingcopper-1.20.1-2.3.2.jar                 |Everything is Copper          |everythingcopper              |1.20.1-2.3.2        |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.2.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.2    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0.jar                       |MixinExtras                   |mixinextras                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.1.8.jar                 |Bookshelf                     |bookshelf                     |20.1.8              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.20.1-3.19.5.988.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |3.19.5.988          |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.20.1-1.6.3.jar                   |Guard Villagers               |guardvillagers                |1.20.1-1.6.3        |DONE      |Manifest: NOSIGNATURE
		createdieselgenerators-1.20.1-1.2f.jar            |Create Diesel Generators      |createdieselgenerators        |1.20.1-1.2f         |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.1.0forge-mc1.20.1.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |DONE      |Manifest: NOSIGNATURE
		ironshulkerbox-1.20.1-5.3.2.jar                   |Iron Shulker Boxes            |ironshulkerbox                |1.20.1-5.3.2        |DONE      |Manifest: NOSIGNATURE
		Steam_Rails-1.5.3forge-mc1.20.1.jar               |Create: Steam 'n' Rails       |railways                      |1.5.3+forge-mc1.20.1|DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.5    |DONE      |Manifest: NOSIGNATURE
		macawsroofsbop-1.20-1.0.jar                       |Macaw's Roofs - BOP           |macawsroofsbop                |1.20-1.0            |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		shetiphiancore-forge-1.20.1-1.2.jar               |ShetiPhian-Core               |shetiphiancore                |1.20.1-1.2          |DONE      |Manifest: NOSIGNATURE
		ctov-3.3.6.jar                                    |ChoiceTheorem's Overhauled Vil|ctov                          |3.3.6               |DONE      |Manifest: NOSIGNATURE
		absentbydesign-1.20.1-1.8.0.jar                   |Absent By Design Mod          |absentbydesign                |1.8.0               |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		twilightforest-1.20.1-4.3.1893-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1893            |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.12.4.jar                         |Refined Storage               |refinedstorage                |1.12.4              |DONE      |Manifest: NOSIGNATURE
		fixexperiencebug-1.20-46.2.2.jar                  |Experience Bug Fix            |experiencebugfix              |46.2.2              |DONE      |Manifest: NOSIGNATURE
		easy_piglins-1.20.1-1.0.1.jar                     |Easy Piglins                  |easy_piglins                  |1.20.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.20.1-2.16.0.jar                   |Structure Gel API             |structure_gel                 |2.16.0              |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.1.1-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.20.1-3.5.14.jar            |Industrial Foregoing          |industrialforegoing           |3.5.14              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		Amplified_Nether_1.20.2_v1.2.3.jar                |Amplified Nether              |amplifiednether               |1.2.3               |DONE      |Manifest: NOSIGNATURE
		Compressium-3.0.2-build.12mc1.20.jar              |Compressium                   |compressium                   |3.0.2-build.12+mc1.2|DONE      |Manifest: NOSIGNATURE
		explorify-v1.3.0-mc1.20.jar                       |Explorify                     |explorify                     |1.3.0-mc1.20        |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.20.1forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.20.1.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		trimeffects-1.1.0-forge.jar                       |Trim Effects                  |trimeffects                   |1.1.0-forge         |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.4.71.20.1.jar                      |Curios API                    |curios                        |5.4.7+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		collective-1.20.1-7.30.jar                        |Collective                    |collective                    |7.30                |DONE      |Manifest: NOSIGNATURE
		Searchables-forge-1.20.1-1.0.2.jar                |Searchables                   |searchables                   |1.0.2               |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-9.1.6.jar                            |FramedBlocks                  |framedblocks                  |9.1.6               |DONE      |Manifest: NOSIGNATURE
		dungeons-and-taverns-3.0.3 [Forge].jar            |Dungeons and Taverns          |mr_dungeons_andtaverns        |3.0.3               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.20.1-lex-1.9.jar                     |Elevator Mod                  |elevatorid                    |1.20.1-lex-1.9      |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		cumulus_menus-1.20.1-1.0.0-neoforge.jar           |Cumulus                       |cumulus_menus                 |1.20.1-1.0.0-neoforg|DONE      |Manifest: NOSIGNATURE
		constructionwand-1.20.1-2.11.jar                  |Construction Wand             |constructionwand              |1.20.1-2.11         |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.2.4b-mc1.20.1forge.jar                |Macaw's Roofs                 |mcwroofs                      |2.2.4b              |DONE      |Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.20.1-forge-1.108.4.jar               |CC: Tweaked                   |computercraft                 |1.108.4             |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.2.1-mc1.20.1forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.1               |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.1.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.1          |DONE      |Manifest: NOSIGNATURE
		flib-1.20.1-0.0.11.jar                            |flib                          |flib                          |0.0.11              |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		YungsBetterEndIsland-1.20-Forge-2.0.4.jar         |YUNG's Better End Island      |betterendisland               |1.20-Forge-2.0.4    |DONE      |Manifest: NOSIGNATURE
		nitrogen_internals-1.20.1-1.0.1-neoforge.jar      |Nitrogen                      |nitrogen_internals            |1.20.1-1.0.1-neoforg|DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.20.1-forge-5.2.2.jar                 |Jade Addons                   |jadeaddons                    |5.2.2               |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		bwncr-forge-1.20.1-3.17.0.jar                     |Bad Wither No Cookie Reloaded |bwncr                         |3.17.0              |DONE      |Manifest: NOSIGNATURE
		deep_aether-1.20.1-1.0.13.jar                     |Deep Aether                   |deep_aether                   |1.20.1-1.0.13       |DONE      |Manifest: NOSIGNATURE
		Towns-and-Towers-1.12-FabricForge.jar             |Towns and Towers              |t_and_t                       |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		letmedespawn-forge-1.20.x-1.2.0.jar               |Let Me Despawn                |letmedespawn                  |1.2.0               |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.6-mc1.20.1forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.20-Forge-2.0.4.jar     |YUNG's Better Jungle Temples  |betterjungletemples           |1.20-Forge-2.0.4    |DONE      |Manifest: NOSIGNATURE
		elytraslot-forge-6.3.01.20.1.jar                  |Elytra Slot                   |elytraslot                    |6.3.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		inventorysorter-1.20.1-23.0.1.jar                 |Simple Inventory Sorter       |inventorysorter               |23.0.1              |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.20-15.1.0.jar                   |TrashSlot                     |trashslot                     |15.1.0              |DONE      |Manifest: NOSIGNATURE
		flatbedrock-forge-3.0.1-build.18mc1.20.1.jar      |Flat Bedrock                  |flatbedrock                   |3.0.1-build.18+mc1.2|DONE      |Manifest: NOSIGNATURE
		treeharvester-1.20.1-8.6.jar                      |Tree Harvester                |treeharvester                 |8.6                 |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		OldCombatMod_1.20.X.jar                           |Old Combat Mod                |old_combat_mod                |1.1                 |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.20.1-10.4.5.19.jar                     |Mekanism                      |mekanism                      |10.4.5              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.20.1-10.4.5.19.jar           |Mekanism: Generators          |mekanismgenerators            |10.4.5              |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.20.1-10.4.5.19.jar                |Mekanism: Tools               |mekanismtools                 |10.4.5              |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.1.01.20.jar                        |Caelus API                    |caelus                        |3.1.0+1.20          |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.3.jar                   |Waystones                     |waystones                     |14.1.3              |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.3.jar                  |Clumps                        |clumps                        |12.0.0.3            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.18-forge.jar                |Journeymap                    |journeymap                    |5.9.18              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-6.3.41.20.1.jar                    |Comforts                      |comforts                      |6.3.4+1.20.1        |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |DONE      |Manifest: NOSIGNATURE
		NetheriteHorseArmor-CJ-forge-mc1.20-1.4.0.jar     |Netherite Horse Armor         |netheritehorsearmor           |1.4.0               |DONE      |Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.20.1-14.0.2.jar      |Farming for Blockheads        |farmingforblockheads          |14.0.2              |DONE      |Manifest: NOSIGNATURE
		neruina-1.2.6-forge1.18.2-1.20.1.jar              |Neruina                       |neruina                       |1.2.6               |DONE      |Manifest: NOSIGNATURE
		CraterLib-forge-1.20-1.0.2.jar                    |CraterLib                     |craterlib                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.20-8.0.3.jar                           |McJtyLib                      |mcjtylib                      |1.20-8.0.3          |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.20-5.0.2.jar                        |RFToolsBase                   |rftoolsbase                   |1.20-5.0.2          |DONE      |Manifest: NOSIGNATURE
		Continents_1.20.4_v1.1.4.jar                      |Continents                    |continents                    |1.1.4               |DONE      |Manifest: NOSIGNATURE
		mininggadgets-1.15.6.jar                          |Mining Gadgets                |mininggadgets                 |1.15.6              |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		silent-gear-1.20.1-3.5.3.jar                      |Silent Gear                   |silentgear                    |3.5.3               |DONE      |Manifest: NOSIGNATURE
		bloodmagic-1.20.1-3.3.2-44.jar                    |Blood Magic                   |bloodmagic                    |3.3.2-44            |DONE      |Manifest: NOSIGNATURE
		scuba_gear-1.20.1-1.0.6.jar                       |Scuba Gear                    |scuba_gear                    |1.0.6               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4.jar                       |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |DONE      |Manifest: NOSIGNATURE
		ZeroCore2-1.20.1-2.1.41.jar                       |Zero CORE 2                   |zerocore                      |1.20.1-2.1.41       |DONE      |Manifest: NOSIGNATURE
		ExtremeReactors2-1.20.1-2.0.77.jar                |Extreme Reactors              |bigreactors                   |1.20.1-2.0.77       |DONE      |Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.592.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.592          |DONE      |Manifest: NOSIGNATURE
		macawsbridgesbop-1.20-1.1.jar                     |Macaw's Bridges - BOP         |macawsbridgesbop              |1.20-1.1            |DONE      |Manifest: NOSIGNATURE
		mcwfencesbop-1.20-1.0.jar                         |Macaw's Fences - BOP          |mcwfencesbop                  |1.20-1.0            |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.8.78-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.78         |DONE      |Manifest: NOSIGNATURE
		titanium-1.20.1-3.8.25.jar                        |Titanium                      |titanium                      |3.8.25              |DONE      |Manifest: NOSIGNATURE
		silent-lib-1.20.1-8.0.0.jar                       |Silent Lib                    |silentlib                     |8.0.0               |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		NoChatReports-FORGE-1.20.1-v2.2.2.jar             |No Chat Reports               |nochatreports                 |1.20.1-v2.2.2       |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.7.1.jar                      |Jade                          |jade                          |11.7.1              |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-15.0.15.jar             |Applied Energistics 2         |ae2                           |15.0.15             |DONE      |Manifest: NOSIGNATURE
		ae2wtlib-15.2.1-forge.jar                         |AE2WTLib                      |ae2wtlib                      |15.2.1-forge        |DONE      |Manifest: NOSIGNATURE
		HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7.jar   |HopoBetterRuinedPortals       |hoporp                        |1.3.7               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.14+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.14+1.20.1      |DONE      |Manifest: NOSIGNATURE
		aeroblender-1.20.1-1.0.1-neoforge.jar             |AeroBlender                   |aeroblender                   |1.20.1-1.0.1-neoforg|DONE      |Manifest: NOSIGNATURE
		EnderIO-1.20.1-6.0.23-alpha.jar                   |Ender IO                      |enderio                       |6.0.23-alpha        |DONE      |Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |DONE      |Manifest: NOSIGNATURE
		rftoolsbuilder-1.20-6.0.3.jar                     |RFToolsBuilder                |rftoolsbuilder                |1.20-6.0.3          |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.20.1-1.0.17.jar                  |Easy Villagers                |easy_villagers                |1.20.1-1.0.17       |DONE      |Manifest: NOSIGNATURE
		pipez-1.20.1-1.2.5.jar                            |Pipez                         |pipez                         |1.20.1-1.2.5        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		EasyEmerald-Forge-1.20.1-1.5.3.jar                |Easy Emerald                  |easy_emerald                  |1.4.15              |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.49.21.20.1.jar                  |Polymorph                     |polymorph                     |0.49.2+1.20.1       |DONE      |Manifest: NOSIGNATURE
		refinedpolymorph-0.1.0-1.20.1.jar                 |Refined Polymorphism          |refinedpolymorph              |0.1.0-1.20.1        |DONE      |Manifest: NOSIGNATURE
		polyeng-forge-0.1.0-1.20.1.jar                    |Polymorphic Energistics       |polyeng                       |0.1.0-1.20.1        |DONE      |Manifest: NOSIGNATURE
		[1.20.1] SecurityCraft v1.9.8.jar                 |SecurityCraft                 |securitycraft                 |1.9.8               |DONE      |Manifest: NOSIGNATURE
		storagedrawers-1.20.1-12.0.2.jar                  |Storage Drawers               |storagedrawers                |12.0.2              |DONE      |Manifest: NOSIGNATURE
		enderchests-forge-1.20.1-1.2.jar                  |EnderChests                   |enderchests                   |1.20.1-1.2          |DONE      |Manifest: NOSIGNATURE
		TrampleNoMore-Forge-1.20.1-13.0.2.jar             |TrampleNoMore                 |tramplenomore                 |13.0.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		lootr-1.20-0.7.30.73.jar                          |Lootr                         |lootr                         |0.7.29.68           |DONE      |Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		solcarrot-1.20.1-1.15.1.jar                       |Spice of Life: Carrot Edition |solcarrot                     |1.15.1              |DONE      |Manifest: NOSIGNATURE
		arclight-1.20.1-1.0.2-SNAPSHOT-71acd73.jar        |Arclight Mod                  |arclight                      |1.20.1-1.0.2-SNAPSHO|DONE      |Manifest: NOSIGNATURE
		cosmeticarmorreworked-1.20.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		OpenLoader-Forge-1.20.1-19.0.3.jar                |OpenLoader                    |openloader                    |19.0.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		cristellib-1.1.5-forge.jar                        |Cristel Lib                   |cristellib                    |1.1.5               |DONE      |Manifest: NOSIGNATURE

**Comment by darksonic300** [comment]
This issue is already fixed in the latest release.
