### ISSUE TITLE
deep_aether:yagroot_roots are tagged as minecraft:saplings

### ISSUE THREAD

**Issue by TelepathicGrunt** [TunefulTurnip/Deep-Aether#136]
Is it intended that the yagroot_roots which looks like a mangrove root-like block is tagged as minecraft:saplings? It shows up when a mod tries to get blocks from that tag which seems odd
https://github.com/RazorDevs/Deep-Aether/blob/70268e6c523fa9c742bdfe01d78e23e288159b7b/src/generated/resources/data/minecraft/tags/items/saplings.json#L8

**Comment by darksonic300** [comment]
That is not intended.
