### ISSUE TITLE
Crash on Generated Chunk ("Unable to get Y-rotated facing of up")

### ISSUE THREAD

**Issue by Gammaboy45** [TunefulTurnip/Deep-Aether#138]
https://pastebin.com/zht1WJvv

Recurring crash when attempting to generate one specific chunk. Rollbacks after reloading the world are safe. Logs suggest to me a fallen log is somehow causing the crash, however I've seen successfully generated hollow fallen log features before (unless this one is a specific variant?)

I've been approaching the chunk on a Moa, may attempt without one but I doubt this contributes to the error. Other mods (dominantly other Aether addons, not a modpack) are installed, could likely be a mod conflict. Notable nearby addon structure is a lost aether platinum dungeon.

**Comment by TunefulTurnip** [comment]
I wasn't able to replicate this issue, since it only seem to happen very rarely, but it should be fixed for the next release. Please reopen this issue if the issue still occurs after the next release. The next release haven't been released yet, but we're planning to get it out relatively soon.
