### ISSUE TITLE
Certain Terrain Features don't generate under Overhangs

### ISSUE THREAD

**Issue by Builderdog841** [TunefulTurnip/Deep-Aether#144]
Noticeable ones: Golden Heights Grass, Aerlavender Patches and Aether Moss Patches, though there are probably more. It's caused by these features not having the Improved Layer Placement in the Placed Features

**Comment by TunefulTurnip** [comment]
For the Golden Heights Grass and the Aerlavender Patches is it intended behaviour. The grass generates with the moss inside the Aether Moss Patches feature so the Improved Layer Placement isn't needed here.
