### ISSUE TITLE
Poison Lakes Overlap

### ISSUE THREAD

**Issue by Builderdog841** [TunefulTurnip/Deep-Aether#145]
The Fix would be to have them generate chunk whise again like in previous versions

![2024-01-19_23 11 44](https://github.com/RazorDevs/Deep-Aether/assets/81527321/fc39cdff-bfe2-4814-b23d-96e71c3fb39a)

**Comment by TunefulTurnip** [comment]
I'll probably not change the poison lakes to generate them chunk wise, since that creates a weird pattern

**Comment by Zepalesque** [comment]
so I know this is marked as won’t fix, but I feel like this might still be a good idea to do, considering that it’s randomized anyway, not like in any kind of repeating pattern, so it’d still look fairly natural
plus, the border pattern is not likely noticeable if you’re just traversing the aether in survival, and you’d have to _really_ look for it when in creative anyway, and you’d only be able to really tell is if you had chunk borders on
