### ISSUE TITLE
Aerwhale texture broke

### ISSUE THREAD

**Issue by MikroChris** [TunefulTurnip/Deep-Aether#153]
Hello, I've just downloaded the new update, and noticed the texture from the aerwhale broke a little bit

I also have aether:redux installed, idk if it is the problem

![2024-01-21_21 45 44](https://github.com/RazorDevs/Deep-Aether/assets/136250376/b3586d50-d2a7-4037-8be5-3206f1dc6309)

**Comment by darksonic300** [comment]
This is not the first time the issue was reported, but we weren't able to reproduce it.
First, what version is this? Can you verify if this also happens without Aether: Redux?
Also is this a new world?
Would be happy to help if there's anything else you noticed.

**Comment by MikroChris** [comment]
Aether 1.20.1  1.1.0 
Deep aether 1.20.1 1.0.1
It was a previous world
I made a new world and deleted the aether:redux, but it's still broken

**Comment by darksonic300** [comment]
Ok then, looking into that
