### ISSUE TITLE
[Suggestion] Add {wood_type}_logs tags

### ISSUE THREAD

**Issue by VoidLeech** [TunefulTurnip/Deep-Aether#155]
Vanilla has tags such as oak_logs for both blocks and items that contain the log, stripped log, wood and stripped wood of a wood type (and many mods follow suit, Aether included). Deep Aether currently does not.
This would be nice to have for mod developers that wish to add compatibility with Deep Aether.

**Comment by darksonic300** [comment]
Sounds more like an oversight on our side, fixed that.
