### ISSUE TITLE
Yagroot roots are part of leaves tag

### ISSUE THREAD

**Issue by VoidLeech** [TunefulTurnip/Deep-Aether#161]
Yagroot Roots are assigned the [leaves](https://github.com/RazorDevs/Deep-Aether/blob/1.20.1-1.0/src/generated/resources/data/minecraft/tags/blocks/leaves.json) tag, even though vanilla's mangrove roots are not. (Which seem like the closest parallel)
This means the roots instamine with shears, which mangrove's don't, with a tool made from non-Aether materials. 
Could be a design decision w.r.t. mods that chop trees from a single block (and those probably only checking for mangrove roots specifically), but seems like an oversight.

**Comment by darksonic300** [comment]
Thank you for reporting it anyways, but for now it is a choice we decided to stick with.
Still I won't close the issue yet as we don't really know if there will be many negative implications with it, so we might change that in the future.
