### ISSUE TITLE
Update mod to 1.19.1

### ISSUE THREAD

**Issue by TunefulTurnip** [TunefulTurnip/Deep-Aether#17]
- [x] Re add Music disc
- [x] Re add Entities
- [x] Re add posion bucket

**Comment by TunefulTurnip** [comment]
- [ ] Re add Music disc
- [ ] Re add Entities
- [ ] Re add posion bucket
- [ ]

**Comment by darksonic300** [comment]
Music Discs ported back from 1.18.2.
