### ISSUE TITLE
[Bug] Crash When Trying to Place Down Vines From Mod

### ISSUE THREAD

**Issue by serioos** [TunefulTurnip/Deep-Aether#175]
### Forge/Neoforge Version

Forge 47.2.20

### Deep Aether Version

deep_aether-1.20.1-1.0.3

### Terrablender Version

TerraBlender-forge-1.20.1-3.0.1.4

### Aether Version

aether-1.20.1-1.4.0-neoforge

### Log Files

[crash-2024-04-23_05.09.41-client.txt](https://github.com/RazorDevs/Deep-Aether/files/15072716/crash-2024-04-23_05.09.41-client.txt)
[latest.log](https://github.com/RazorDevs/Deep-Aether/files/15072717/latest.log)

### Bug Report

I tried to place down one of the vines from the Deep Aether mod to decorate my home with it (it was purple vines) and it instantly crashed my game.

![2024-04-23_05 09 48](https://github.com/RazorDevs/Deep-Aether/assets/93765296/292af626-fb19-4bc1-89a7-1de8477fa32f)

**Comment by darksonic300** [comment]
Might be an issue with Sinytra Connector. Also, does this happen everytime you place the vines?

**Comment by serioos** [comment]
I just now tried again to make sure, and yes it crashes every time when I want to place it down.

**Comment by TunefulTurnip** [comment]
This issue is most likely a conflict with another mod. Try to remove mods until you find out what mod is causing the issue

**Comment by serioos** [comment]
I tested it some more, and it seems placing the vines down crashes the game only when I am trying to place them on half slabs. It crashed for me on top half slab every time. I can place it on full block just fine.

**Comment by darksonic300** [comment]
Oh that helps a lot more, I was having some trouble figuring out why that was happening.
