### ISSUE TITLE
Yagroot Vines cause crash when placed on Yagroot Plank Stairs

### ISSUE THREAD

**Issue by Cryophoenix** [TunefulTurnip/Deep-Aether#185]
### Forge/Neoforge Version

forge 47.2.30

### Deep Aether Version

1.0.3

### Terrablender Version

3.0.1.4

### Aether Version

1.4.0

### Log Files

[crash-2024-06-03_22.02.55-client.txt](https://github.com/user-attachments/files/15571770/crash-2024-06-03_22.02.55-client.txt)

### Bug Report

Right clicking a Yagroot Vine against the front or side of a Yagroot Stair (not full block) causes a client-sided crash. The vines can be placed on the backside (full block) without issue.

Expected result: Right clicking on it shouldn't place the vine, because it's not a solid surface, but it also shouldn't crash the user.
Actual result: The client suffers from a null error and crashes.

Theory: There isn't a check when the yagroot vine is placed for whether the block clicked upon is a full block or not, and so the client tries to render what isn't there and consequently crashes.

**Comment by TunefulTurnip** [comment]
Fixed in upcoming release
