### ISSUE TITLE
Server crash, Forge 1.20.1

### ISSUE THREAD

**Issue by Venes-Art** [TunefulTurnip/Deep-Aether#186]
### Forge/Neoforge Version

Forge-1.20.1

### Deep Aether Version

1.0.3

### Terrablender Version

3.0.1.4

### Aether Version

1.1.0

### Log Files

[crash-2024-06-05_16.22.47-fml.txt](https://github.com/user-attachments/files/15593722/crash-2024-06-05_16.22.47-fml.txt)

### Bug Report

Mod itself works perfectly fine on the client side, but crashes the game when put on the server.

**Comment by darksonic300** [comment]
Your Aether version is ancient, you shouldn't be able to play client-side either

**Comment by Venes-Art** [comment]
But it worked somehow. Yeah, I noticed that Aether is probably older than me :) I'm going to upgrade it and let you know if bug exists

**Comment by darksonic300** [comment]
Closing this.
