### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Melanomass** [TunefulTurnip/Deep-Aether#188]
### Forge/Neoforge Version

neoforge-47.1.106

### Deep Aether Version

1.0.4

### Terrablender Version

3.0.1.7

### Aether Version

1.4.2

### Log Files

[latest.log](https://github.com/user-attachments/files/15890697/latest.log)

### Bug Report

[crash-2024-06-18_19.59.22-client.txt](https://github.com/user-attachments/files/15890714/crash-2024-06-18_19.59.22-client.txt)

The game does not start. So the list of mods is the only valid element. By disabling Deep Aether, the game launches without crashing. Thank you for your time

**Comment by darksonic300** [comment]
Seems like an incompatibility with Delightful. I'm going to investigate this.

**Comment by Melanomass** [comment]
Yes I play with delightful. Thank you for your reactivation.
where did you find the error with the latter?

**Comment by darksonic300** [comment]
The issue is related to the fact that we've made some changes to our file locations, causing the locations determined in Delightful to point to wrong places.

**Comment by darksonic300** [comment]
I think I'll report this to the Delightful Issues page, so they can fix the issue.

**Comment by Melanomass** [comment]
Thank you very much for your help, I will disable delightful in the meantime.

**Comment by darksonic300** [comment]
At best you can use Deep Aether's previous version in the meantime.

**Comment by Melanomass** [comment]
Ah, yes I can do that too lol
