### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SafeOfArsenal** [TunefulTurnip/Deep-Aether#189]
### Forge/Neoforge Version

Forge 47.3.1

### Deep Aether Version

1.0.4 

### Terrablender Version

3.0.1.7

### Aether Version

1.4.2

### Log Files

[latest.log](https://github.com/user-attachments/files/15922019/latest.log)

### Bug Report

the game crashes when opening it and i expect it to open as normal

**Comment by darksonic300** [comment]
As said in other issues, we made changes so there's incompatibility with Delightful. This will be fixed in their next release, so revert to 1.0.3 for now
