### ISSUE TITLE
Crash When Opening Game With Modpack

### ISSUE THREAD

**Issue by WolWolffz** [TunefulTurnip/Deep-Aether#190]
### Forge/Neoforge Version

forge-4.2.16

### Deep Aether Version

1.0.4

### Terrablender Version

3.0.1.7

### Aether Version

1.4.2

### Log Files

[latest.log](https://github.com/user-attachments/files/15930603/latest.log)
[crash-2024-06-21_13.46.04-client.txt](https://github.com/user-attachments/files/15930618/crash-2024-06-21_13.46.04-client.txt)

### Bug Report

The game crashes when opening with my modpack. Since when i remove Deep Aether from the modpack the game works fine, i assumed its a problem related to Deep Aether (what caught my attention was a NoClassDefFoundError with SkyJade Weapon). If it is not related to Deep Aether i apologize for the inconvenience and would be happy if u guys could point out which mod is actually the problem so i can report the bug to them, thanks a lot.

**Comment by darksonic300** [comment]
I'll have to create some sort of pin here on github soon.
We changed some class locations and Delightful is going to fix that in their next release, so revert to the older DA version
