### ISSUE TITLE
If Deep Aether crashes your game, read this.

### ISSUE THREAD

**Issue by darksonic300** [TunefulTurnip/Deep-Aether#191]
If you're playing in a modpack with Delightful or some other mods that add compatibility with Deep Aether, and your game crashes, then read this.

We made some changes in our workspace, moving some parts of the code in better places to better organize everything. This means that mods like Delightful which reference these parts of the code have to be updated, so that they point to the right location.

Delightful is going to fix this soon, but there might be other mods that crash for the same reason and in that case we'd like you to report them to us so we can notice the authors and fix the issue.

**Comment by MokahTGS** [comment]
Getting a crash, and I'm not sure if it is related: https://pastebin.com/qaczq0SC

**Comment by darksonic300** [comment]
Nope, that is actually with Aether Redux you're having issues with.
Though there are some mod combinations which would cause more crashes

**Comment by darksonic300** [comment]
Also this was fixed so I better close that. Close your issue on the other side since Aether Redux's dev already reported the issue
