### ISSUE TITLE
1.20.1 Log Spam 🔥

### ISSUE THREAD

**Issue by Krimatoria** [TunefulTurnip/Deep-Aether#194]
### Forge/Neoforge Version

Forge 47.3.5

### Deep Aether Version

1.0.4

### Terrablender Version

3.0.1.7

### Aether Version

1.4.2

### Log Files

<html>
<body>

[00:21:37] [Worker-ResourceReload-1/ERROR] [minecraft/TagLoader]: No key values in MapLike[{"remove":["deep_aether:golden_grove"]}]
4002

<br class="Apple-interchange-newline">
</body>
</html>

### Bug Report

Log

**Comment by TunefulTurnip** [comment]
Invalid issue. No log was provided.
