### ISSUE TITLE
Aerglow Blossoms Don't Drop Naturally

### ISSUE THREAD

**Issue by joanshattershergame** [TunefulTurnip/Deep-Aether#196]
### Forge/Neoforge Version

1.19.2 Forge 43.3.0

### Deep Aether Version

1.0.2

### Terrablender Version

2.0.1.166

### Aether Version

1.3.1

### Log Files

[latest.log](https://github.com/user-attachments/files/16610216/latest.log)

### Bug Report

Tested this ingame (both 1.0.2 and 1.0.4) with roseroot and blue roseroot trees, as well as radiant orchids, plus directly checked the block drops, recipes, and Book of Lore entries (BoL entries for both flowering roseroot leaves mention that they can decay into aerglow blossoms, entry for aerglow blossoms mentions they drop from flowering roseroot leaves, and radiant orchids don't mention anything about aerglow blossoms, despite their mention on the mod page) of a fresh install of the mod. None of the previously mentioned blocks have blossoms listed in any of their loot tables or recipes, making it unobtainable legitimately in survival, as well as making packed aether mud and aether mud bricks unobtainable, too.

**Comment by TunefulTurnip** [comment]
1.19.2 is no longer supported
