### ISSUE TITLE
Deep Aether crashing on my modpack of 480 mods

### ISSUE THREAD

**Issue by Vocadandia** [TunefulTurnip/Deep-Aether#197]
### Forge/Neoforge Version

Forge 47.3.0 or 47.3.1

### Deep Aether Version

1.0.4

### Terrablender Version

3.0.1.7

### Aether Version

1.4.2

### Log Files

[latest.log](https://github.com/user-attachments/files/16662034/latest.log)

### Bug Report

I tried adding this mod into my modpack that I custom made for my singleplayer gaming, and it crashes my game whenever I try running minecraft. If anything, I have:

The original Aether mod
Lost Aether Content
Aether Villages
Ancient Aether
Aether Delight
and Aether Redux
 
Could there be a compatibility issue or what?

My modpack has 480 mods and I'm not sure what is causing the crash to happen.
I've read the comment section on the curseforge page of Deep Aether and saw something about Delight mods, yes I've tried removing Aether Delight from my mods folder but the issue still persists, and I also sent the whole log cause I don't know myself what could be causing errors.

Can I get an explanation of why the issue occurs when found please?

**Comment by darksonic300** [comment]
Nope, it's not Aether Delight we were having issues with, but Delightful.
You have to update your Delightful version.
