### ISSUE TITLE
<title>Strange recipe for a boat

### ISSUE THREAD

**Issue by Axiang85** [TunefulTurnip/Deep-Aether#202]
### Feature/Idea

abnormal
![2024-10-12_05 06 20](https://github.com/user-attachments/assets/e4011528-c3b8-4fe2-8216-74b43b001933)
![2024-10-12_05 06 36](https://github.com/user-attachments/assets/33b3a66d-cb0c-4f9c-9ea6-872a394c1847)
![2024-10-12_05 06 45](https://github.com/user-attachments/assets/ca774f00-64ff-4d71-a89a-bdf4826cd52c)
![2024-10-12_05 06 56](https://github.com/user-attachments/assets/95fa0e38-86c1-4b81-8ff6-bfbe8605aeee)
![2024-10-12_05 07 10](https://github.com/user-attachments/assets/d3483f44-9b16-4504-8a2a-f9f657053a99)
normal
![2024-10-12_05 08 01](https://github.com/user-attachments/assets/ff154208-ebf6-4df2-a61f-d0abdd388001)

### Value of Proposition

Hope it can become a normal formula

### Credit

- [X] I want to be credited for the idea.

**Comment by darksonic300** [comment]
This is more of a bug than a feature XD
