### ISSUE TITLE
You might not want to have this recipe

### ISSUE THREAD

**Issue by Ganpan14O** [TunefulTurnip/Deep-Aether#208]
### Forge/Neoforge Version

forge-47.3.0

### Deep Aether Version

1.0.4

### Terrablender Version

3.0.1.7

### Aether Version

1.5.1

### Log Files

[latest.log](https://github.com/user-attachments/files/17782888/latest.log)

### Bug Report

![image](https://github.com/user-attachments/assets/937f604d-286f-4d25-8277-deb0cef94c69)
This recipe allows for infinite gravitite when combined with fortune, which I imagine is unintentional.

**Comment by TunefulTurnip** [comment]
This is a compatibility issue with the aether: redux and not deep aether itself
