### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by Qwerty97475** [TunefulTurnip/Deep-Aether#210]
### Forge/Neoforge Version

forge-47.3.0

### Deep Aether Version

1.0.4

### Terrablender Version

3.0.1.7

### Aether Version

1.5.1

### Log Files

Not required for this issue, would yield no useful information

### Bug Report

What happened?
Stratus Ingot is not tagged as #forge:ingots

What was the expected result?
Stratus Ingot should be tagged as #forge:ingots, and maybe #forge:ingots/stratus as well.

Steps to Reproduce
Install Deep Aether and dependencies of the same versions I input earlier, as well as EMI
Load up a new world
Look for the "tags" section of a Stratus ingot, and notice that the Stratus Ingot is tagged as a trim material, but not as an ingot.
Compare this to ingots from Create, Vanilla Minecraft, Aquaculture 2, etc and notice how they are tagged as #forge:ingots, plus usually a type
![image](https://github.com/user-attachments/assets/18262ebb-e9e2-4317-9f97-fce95edea590)

**Comment by TunefulTurnip** [comment]
Fixed in an upcoming release
