### ISSUE TITLE
Roseroot Planks don't craft into a Crafting Table

### ISSUE THREAD

**Issue by 345boneshoss** [TunefulTurnip/Deep-Aether#51]
![image](https://user-images.githubusercontent.com/107210046/234869461-470f8214-4112-44e4-8503-17bae52c49f8.png)
Looks like the roseroot planks don't craft into crafting tables. Maybe check and see if the other new wood types have similar issues.

**Comment by 345boneshoss** [comment]
Looks like the same goes for trying to craft them into chests...

**Comment by TunefulTurnip** [comment]
Already resolved with issue #43

**Comment by 345boneshoss** [comment]
Oh, good!!
