### ISSUE TITLE
Cloudium and Skyjade can't be used for beacon bases and can't be uncrafted 

### ISSUE THREAD

**Issue by JonMyDude** [TunefulTurnip/Deep-Aether#56]
![Screenshot_75](https://user-images.githubusercontent.com/68225410/235369334-89b25644-6725-40f6-9451-6a2484797144.png)
![bruhhh](https://user-images.githubusercontent.com/68225410/235369347-41a4bcee-413a-4c41-ade5-02ac8c8b4d3a.png)
The skyjade and cloudium pickaxes don't work on the slider but from what I can tell you fixed it

**Comment by darksonic300** [comment]
Yup, Slider issue fixed as of now, we'll release a patch build probably next week.
