### ISSUE TITLE
Recipe issues, composting, Biome display name

### ISSUE THREAD

**Issue by JonMyDude** [TunefulTurnip/Deep-Aether#61]
Can't compost the items below
![image](https://user-images.githubusercontent.com/68225410/236679634-568a61b3-4a90-41ad-bf41-7a91651e15dd.png)
Forgot this one
![image](https://user-images.githubusercontent.com/68225410/236681137-1b80b603-cdb1-47ca-878f-61351acac11b.png)

Items below cannot be turned into charcoal
![image](https://user-images.githubusercontent.com/68225410/236681342-9ecd50d0-52c4-40a3-883a-b86dfaba562e.png)

Items below cannot be used as fuel
![image](https://user-images.githubusercontent.com/68225410/236681304-21a1a758-91ca-4677-a9c3-06d9e99f3306.png)
Every chest boat recipe is broken
![image](https://user-images.githubusercontent.com/68225410/236680664-74d2114f-b820-4523-ba79-7425b04ef993.png)
I don't know if this can be changed but the display names on Nature's compass are like this:
![image](https://user-images.githubusercontent.com/68225410/236678068-20f26716-2419-4e08-b1b4-48b4e29df6c0.png)

**Comment by darksonic300** [comment]
No problem, all of these issues can be easily addressed.
