### ISSUE TITLE
Hates Rubidium.

### ISSUE THREAD

**Issue by MagmaSlime123** [TunefulTurnip/Deep-Aether#63]
See https://github.com/Asek3/Rubidium/issues/485.

**Comment by TunefulTurnip** [comment]
Are you sure this is an issue with deep aether? It doesn't look like it on the crash report

**Comment by TunefulTurnip** [comment]
Since rubidium and deep aether works for me I'm going to close this issue. If anyone else has the same problem or I get more information about the issue, the issue can be reopened.
