### ISSUE TITLE
Cloudium Armor Set kicks Client off the server with Internal Server Error (1.19.4)

### ISSUE THREAD

**Issue by IulianDan** [TunefulTurnip/Deep-Aether#68]
Minecraft Version: 1.19.4
Mod Version: 1.0.4
Forge Version: 45.0.59

I'm playing on a Custom Modpack I made for me and my friends, and one of them got a full set of Cloudium armor. But whenever he equips the whole set (including gloves) it kicks him off the server with a simple "Internal Server Error" and I have to go edit his playerfile to delete one of the pieces so he can join back.

Server Console gives this error:
https://pastebin.com/UhWKP3e3

Mod List:
https://pastebin.com/VJPfkYmb

**Comment by darksonic300** [comment]
This is a little issue created by the ability check. Only the player has the armor set, and so the server can't actually check the KeyBind of the ability since it's a client job. Very easy fix and you'll see it in the next beta 1.0.5.
