### ISSUE TITLE
Feature: Titanium Dungeon

### ISSUE THREAD

**Issue by darksonic300** [TunefulTurnip/Deep-Aether#71]
The idea for this dungeon will revolve in a kind of unusual spawning and mechanics.
It will spawn beneath the normal Aether islands, and will of course present a new boss, to be reached with the use of a new system introduced by the 1.1 update. We already have some ideas on the table, but it's too soon to reveal much of it.

- [ ]  Dungeon Structure
- [ ]  Boss
- [ ]  Loot

**Comment by TunefulTurnip** [comment]
I'm going to close this issue for now, since it's not a planned feature for anytime soon. I'll reopen it when needed
