### ISSUE TITLE
Deep Aether planks don't turn into Crafting Tables...

### ISSUE THREAD

**Issue by 345boneshoss** [TunefulTurnip/Deep-Aether#79]
![image](https://github.com/RazorDevs/Deep-Aether/assets/107210046/3269c55b-6993-46f6-98fe-60f7d4a01397)
![image](https://github.com/RazorDevs/Deep-Aether/assets/107210046/a712a109-52dc-4511-9ad9-2e8eaafd40e5)

**Comment by 345boneshoss** [comment]
Nor can they be crafted into chests. Skyroot tools are good though.
![image](https://github.com/RazorDevs/Deep-Aether/assets/107210046/66c9a7ab-6164-43b2-8f2d-7a5b03d6f731)

**Comment by TwentySeventhLetter** [comment]
Submitted a PR for the missing tag file
