### ISSUE TITLE
bug: New quail sounds don't have subtitles

### ISSUE THREAD

**Issue by Zepalesque** [TunefulTurnip/Deep-Aether#80]
**What is the issue?**
The new quail sounds in the latest commits (not the latest curseforge release) don't have subtitles

**How to reproduce**
1. Enable subtitles
2. go near a quail
3. observe "subtitles.deep_aether.quail.ambient"

**Expected Behavior**
it would say "Quail chirps" or something similar

**Comment by ZGStuff** [comment]
hmmmmmm
fix is coming
idk when
