### ISSUE TITLE
Feature Request: Specific biome tag for quail spawns rather than using #aether:is_aether

### ISSUE THREAD

**Issue by Zepalesque** [TunefulTurnip/Deep-Aether#84]
Right now, quail spawns use the #aether:is_aether tag.
This can conflict if other addons have biomes that they don't want to have quails spawn in ~~cough aetherReduxBlight cough~~

My suggestion is a tag including all of the biomes that _should_ have quail spawns in them, so that other addons can easily exclude/include their biomes from/in the quail spawn tag.

**Comment by darksonic300** [comment]
To be honest it already exists, even if it wasn't for that purpose.
The is_not_swamp biome tag.
Let me just change their spawn real quick.
