### ISSUE TITLE
Can't fly in survival mod with other means than creative or spectator

### ISSUE THREAD

**Issue by MLDEG** [TunefulTurnip/Deep-Aether#97]
Hi !
I don't know if it's intentional or not, but with your mod I can't fly with for example an angel ring.
If it's intentional, is it possible to have the possibility of removing this feature with a config line?

I am currently developing a modpack in 1.20.1 and your mod is really great for bringing a breath of fresh air to Aether and unfortunately the fly is deactivated with another means (excluding creative and spectator).

**mod version** : deep_aether-1.20.1-1.0.9.jar
**forge version** : 47.1.47
**aether version** : aether-1.20.1-1.0.0-beta.1.2

Thank you for your attention

**Comment by darksonic300** [comment]
I might have a few ideas on what it could be, but we were not aware of this bug. Gonna look into it very soon.

**Comment by darksonic300** [comment]
Found what the issue is, as I thought Chromatic Aercloud fight check has a slightly wrong logic. Going to fix that.
