### ISSUE TITLE
Ver. 1.19.4-1.0.7 with the Aether 1.19.4 beta 6.1 & beta 6.2 causes a game crash

### ISSUE THREAD

**Issue by Handrail9** [TunefulTurnip/Deep-Aether#98]
Hello, I tried to update to the latest release today and it appears the 1.0.7 update isn't compatible with the beta 6.1 or beta 6.2 of The Aether for 1.19.4. I'm uploading my launchers logs in the logs.txt file attached. Any help/updates are appreciated! :)

Mod List:
Aeroblender 1.19.4-1.0.1
The Aether 1.19.4-beta6.1 (or beta6.2)
Deep Aether 1.19.4-1.0.7
GeckoLib 1.19.4-4.2
TerraBlender 1.19.4-2.2.0.168

[logs.txt](https://github.com/RazorDevs/Deep-Aether/files/12670094/logs.txt)

**Comment by TunefulTurnip** [comment]
Fixed in the next release
