### ISSUE TITLE
1.20.1 Server Error + General

### ISSUE THREAD

**Issue by Andrew5545** [TunefulTurnip/Deep-Aether#99]
Version: 1.20.1
Forge Version: 47.1.46
Bugs: Logging & Gameplay 
Gameplay: Tree's added via Deep Aether have normal minespeed with overworld tools 
Bugs: Numerous Console Errors in server boot relating to loot tables, tags 
`[Worker-Main-8/ERROR] [net.minecraftforge.common.ForgeHooks/]: Couldn't parse element loot_tables:deep_aether:blocks/stripped_conberry_log_wall
[net.minecraftforge.common.ForgeHooks/]: Couldn't parse element loot_tables:deep_aether:blocks/gilded_holystone_tile_stairs
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'deep_aether:gilded_holystone_tile_stairs'
[Worker-Main-8/ERROR] [net.minecraftforge.common.ForgeHooks/]: Couldn't parse element loot_tables:deep_aether:blocks/stripped_cruderoot_log_wall
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'deep_aether:stripped_cruderoot_log_wall'`
and quite a few more, but It's better not flood the page with these simple errors

**Comment by darksonic300** [comment]
Could you link a pastebin with the entire log? I would like to take a better look at it.
The mining speed is easily fixable.
Does the server run at all?

**Comment by Andrew5545** [comment]
> Could you link a pastebin with the entire log? I would like to take a better look at it. The mining speed is easily fixable. Does the server run at all?

https://pastebin.com/cvuxJKhH
And Yeah server runs, but it just creates a lot of initial boot log spam

**Comment by darksonic300** [comment]
These are all errors related to addon recipies and tags. They throw error when not present because the addon objects are not registered, so there's really not that much we can do about that
